version: "3.8"

services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    networks:
      - wha2eat_network

  redis:
    image: "redis:alpine"
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis_data
    networks:
      - wha2eat_network

volumes:
  redis_data:

networks:
  wha2eat_network:
    driver: bridge
